INSERT INTO cities(id,sort,name_bn,name_en) VALUES (2,1,"ঢাকা","Dhaka");
INSERT INTO cities(id,sort,name_bn,name_en) VALUES (4,2,"রাজশাহী","Rajshahi");
INSERT INTO cities(id,sort,name_bn,name_en) VALUES (3,3,"চট্টগ্রাম","Chittagong");
INSERT INTO cities(id,sort,name_bn,name_en) VALUES (6,4,"খুলনা","Khulna");
INSERT INTO cities(id,sort,name_bn,name_en) VALUES (43,5,"বরিশাল","Barisal");
INSERT INTO cities(id,sort,name_bn,name_en) VALUES (5,6,"সিলেট","Sylhet");
INSERT INTO cities(id,sort,name_bn,name_en) VALUES (8,7,"রংপুর","Rangpur");
INSERT INTO cities(id,sort,name_bn,name_en) VALUES (53,8,"কক্সবাজার","Cox's Bazar");
INSERT INTO cities(id,sort,name_bn,name_en) VALUES (13,9,"কিশোরগঞ্জ","Kishoreganj");
INSERT INTO cities(id,sort,name_bn,name_en) VALUES (36,10,"কুড়িঁগ্রাম","Kurigram");
INSERT INTO cities(id,sort,name_bn,name_en) VALUES (52,11,"কুমিল্লা","Comilla");
INSERT INTO cities(id,sort,name_bn,name_en) VALUES (68,12,"কুষ্টিয়া","Kushtia");
INSERT INTO cities(id,sort,name_bn,name_en) VALUES (55,13,"খাগড়াছড়ি","Khagrachari");
INSERT INTO cities(id,sort,name_bn,name_en) VALUES (35,14,"গাইবান্ধা ","Gaibandha");
INSERT INTO cities(id,sort,name_bn,name_en) VALUES (10,15,"গাজীপুর","Gazipur");
INSERT INTO cities(id,sort,name_bn,name_en) VALUES (11,16,"গোপালগঞ্জ ","Gopalganj");
INSERT INTO cities(id,sort,name_bn,name_en) VALUES (50,17,"চাঁদপুর","Chandpur");
INSERT INTO cities(id,sort,name_bn,name_en) VALUES (30,18,"চাঁপাইনবাবগঞ্জ","Chapai Nawabganj");
INSERT INTO cities(id,sort,name_bn,name_en) VALUES (64,19,"চুয়াডাঙ্গা ","Chuadanga");
INSERT INTO cities(id,sort,name_bn,name_en) VALUES (27,20,"জয়পুরহাট","Joypurhat");
INSERT INTO cities(id,sort,name_bn,name_en) VALUES (12,21,"জামালপুর ","Jamalpur");
INSERT INTO cities(id,sort,name_bn,name_en) VALUES (45,22,"ঝালকাঠি","Jhalokati");
INSERT INTO cities(id,sort,name_bn,name_en) VALUES (66,23,"ঝিনাইদহ","Jhenaidah");
INSERT INTO cities(id,sort,name_bn,name_en) VALUES (25,24,"টাঙ্গাইল","Tangail");
INSERT INTO cities(id,sort,name_bn,name_en) VALUES (41,25,"ঠাকুরগাঁও ","Thakurgaon");
INSERT INTO cities(id,sort,name_bn,name_en) VALUES (34,26,"দিনাজপুর","Dinajpur");
INSERT INTO cities(id,sort,name_bn,name_en) VALUES (28,27,"নওগাঁ","Naogaon");
INSERT INTO cities(id,sort,name_bn,name_en) VALUES (71,28,"নড়াইল ","Narail");
INSERT INTO cities(id,sort,name_bn,name_en) VALUES (20,29,"নরসিংদী ","Narsingdi");
INSERT INTO cities(id,sort,name_bn,name_en) VALUES (29,30,"নাটোর","Natore");
INSERT INTO cities(id,sort,name_bn,name_en) VALUES (18,31,"নারায়ণগঞ্জ","Narayanganj");
INSERT INTO cities(id,sort,name_bn,name_en) VALUES (38,32,"নীলফামারী","Nilphamari");
INSERT INTO cities(id,sort,name_bn,name_en) VALUES (21,33,"নেত্রকোনা","Netrokona");
INSERT INTO cities(id,sort,name_bn,name_en) VALUES (57,34,"নোয়াখালী","Noakhali");
INSERT INTO cities(id,sort,name_bn,name_en) VALUES (39,35,"পঞ্চগড়","Panchagarh");
INSERT INTO cities(id,sort,name_bn,name_en) VALUES (46,36,"পটুয়াখালী","Patuakhali");
INSERT INTO cities(id,sort,name_bn,name_en) VALUES (31,37,"পাবনা","Pabna");
INSERT INTO cities(id,sort,name_bn,name_en) VALUES (47,38,"পিরোজপুর","Pirojpur");
INSERT INTO cities(id,sort,name_bn,name_en) VALUES (9,39,"ফরিদপুর","Faridpur");
INSERT INTO cities(id,sort,name_bn,name_en) VALUES (54,40,"ফেনী","Feni");
INSERT INTO cities(id,sort,name_bn,name_en) VALUES (26,41,"বগুড়া","Bogra");
INSERT INTO cities(id,sort,name_bn,name_en) VALUES (42,42,"বরগুনা","Barguna");
INSERT INTO cities(id,sort,name_bn,name_en) VALUES (63,43,"বাগেরহাট&nbsp;","Bagerhat");
INSERT INTO cities(id,sort,name_bn,name_en) VALUES (48,44,"বান্দরবান","Bandarban");
INSERT INTO cities(id,sort,name_bn,name_en) VALUES (49,45,"ব্রাহ্মণবাড়িয়া","Brahmanbaria");
INSERT INTO cities(id,sort,name_bn,name_en) VALUES (44,46,"ভোলা","Bhola");
INSERT INTO cities(id,sort,name_bn,name_en) VALUES (17,47,"ময়মনসিংহ","Mymensingh");
INSERT INTO cities(id,sort,name_bn,name_en) VALUES (69,48,"মাগুরা","Magura");
INSERT INTO cities(id,sort,name_bn,name_en) VALUES (14,49,"মাদারীপুর","Madaripur");
INSERT INTO cities(id,sort,name_bn,name_en) VALUES (15,50,"মানিকগঞ্জ","Manikganj");
INSERT INTO cities(id,sort,name_bn,name_en) VALUES (16,51,"মুন্সিগঞ্জ","Munshiganj");
INSERT INTO cities(id,sort,name_bn,name_en) VALUES (70,52,"মেহেরপুর","Meherpur");
INSERT INTO cities(id,sort,name_bn,name_en) VALUES (60,53,"মৌলভী বাজার ","Maulvibazar");
INSERT INTO cities(id,sort,name_bn,name_en) VALUES (65,54,"যশোর","Jessore");
INSERT INTO cities(id,sort,name_bn,name_en) VALUES (58,55,"রাঙ্গামাটি ","Rangamati");
INSERT INTO cities(id,sort,name_bn,name_en) VALUES (22,56,"রাজবাড়ী","Rajbari");
INSERT INTO cities(id,sort,name_bn,name_en) VALUES (56,57,"লক্ষ্মীপুর","Lakshmipur");
INSERT INTO cities(id,sort,name_bn,name_en) VALUES (37,58,"লালমনিরহাট","Lalmonirhat");
INSERT INTO cities(id,sort,name_bn,name_en) VALUES (23,59,"শরিয়তপুর","Shariatpur");
INSERT INTO cities(id,sort,name_bn,name_en) VALUES (24,60,"শেরপুর","Sherpur");
INSERT INTO cities(id,sort,name_bn,name_en) VALUES (72,61,"সাতক্ষীরা  ","Satkhira");
INSERT INTO cities(id,sort,name_bn,name_en) VALUES (33,62,"সিরাজগঞ্জ","Sirajgonj");
INSERT INTO cities(id,sort,name_bn,name_en) VALUES (61,63,"সুনামগঞ্জ ","Sunamganj");
INSERT INTO cities(id,sort,name_bn,name_en) VALUES (59,64,"হবিগঞ্জ","Habiganj");
