version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        image: sod-api-master
        container_name: sod-api-master-app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
            - ./storage/logs:/var/www/html/storage/logs
        networks:
            commonservices_common:
                aliases:
                    - sod-api
        extra_hosts:
            - "host.docker.internal:host-gateway"

    webserver:
        image: nginx:alpine
        container_name: sod-api-webserver
        restart: unless-stopped
        ports:
            - 9090:80
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - commonservices_common

networks:
    commonservices_common:
        external: true
